<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ceml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>ceml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*(involves|gather|nab|teams of)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.assignment.ceml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.assume.ceml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ceml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.roles.ceml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\d-]+|many)\s+([\w-]+)</string>
					<key>name</key>
					<string>meta.rolecount.ceml</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.assignment.ceml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(within)</string>
					<key>name</key>
					<string>radius</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.assignment.ceml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(and)</string>
					<key>name</key>
					<string>radius</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(tell)\s+([\w-]+)\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.assignment.ceml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.roles.ceml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.ceml</string>
			<key>end</key>
			<string>^\b</string>
			<key>name</key>
			<string>meta.tell.ceml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#linkvars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#popups</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(ask)\s+([\w-]+)\s*(re)\s*([\w-]+):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.assignment.ceml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.roles.ceml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.assignment.ceml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.roles.ceml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.ceml</string>
			<key>end</key>
			<string>^\b</string>
			<key>name</key>
			<string>meta.ask.ceml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#linkvars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#popups</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.offering.ceml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.ceml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(offers)\s+(.*)$</string>
			<key>name</key>
			<string>meta.offering.ceml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(type|for|rank|within|lasting|takes|req|popularity|players|from|provides|in|join|cue|end|exit|after|join_cue|cue_act)\b</string>
			<key>name</key>
			<string>support.variable.ceml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(many|within|re)\b</string>
			<key>name</key>
			<string>support.constant.ceml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(context|askfor)\b</string>
			<key>name</key>
			<string>keyword.control.ceml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.idea.ceml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.idea.ceml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(snippet|to|ask|within)\s+([.a-zA-Z0-9_/-]+)</string>
			<key>name</key>
			<string>meta.moo.ceml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.js</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+m?\b</string>
			<key>name</key>
			<string>constant.numeric.ceml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=\w):\s+</string>
			<key>contentName</key>
			<string>string.unquoted.ceml</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.assign-stanza.ceml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#linkvars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#popups</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ceml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#linkvars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#popups</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.ceml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>linkvars</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>source.ceml.embedded.ceml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\|([\w\.-]+)\|</string>
			<key>name</key>
			<string>meta.variable.parameter.ceml</string>
		</dict>
		<key>popups</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.quote.popup.ceml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)(.*?)(\])</string>
			<key>name</key>
			<string>meta.popup.ceml</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ceml</string>
	<key>uuid</key>
	<string>BE4CE07F-C4D9-40FE-82BB-2BB28B2DE828</string>
</dict>
</plist>
