require 'treetop'

require 'ceml/lang/script'
require 'ceml/lang/casting_statement'
require 'ceml/lang/basic_instruction'
require 'ceml/lang/instruction_statements'
require 'ceml/lang/tt/lexer'
require 'ceml/lang/tt/casting'
require 'ceml/lang/tt/instructions'
require 'ceml/lang/tt/scripts'
